In [19]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [20]:
import pandas as pd

In [21]:
file_path = '/content/drive/My Drive/Colab Notebooks/googleplaystoredata.csv'
dataset = pd.read_csv(file_path)
dataset.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [22]:
dataset['Category'] = dataset['Category'].str.replace('_',' ').str.lower()

In [23]:
dataset.head(3)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,art and design,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,art and design,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",art and design,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up

In [24]:
dataset['Genres'].value_counts()

Genres
Tools                       842
Entertainment               623
Education                   549
Medical                     463
Business                    460
                           ...
Role Playing;Brain Games      1
Strategy;Education            1
Racing;Pretend Play           1
Communication;Creativity      1
Strategy;Creativity           1
Name: count, Length: 119, dtype: int64

In [25]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10840 non-null  object
 1   Category        10840 non-null  object
 2   Rating          9366 non-null   float64
 3   Reviews         10840 non-null  int64
 4   Size            10840 non-null  object
 5   Installs        10840 non-null  object
 6   Type            10839 non-null  object
 7   Price           10840 non-null  object
 8   Content Rating  10840 non-null  object
 9   Genres          10840 non-null  object
 10  Last Updated    10840 non-null  object
 11  Current Ver     10832 non-null  object
 12  Android Ver     10838 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.1+ MB

In [26]:
dataset['Genres'] = dataset['Genres'].str.replace(';',' ')

In [30]:
dataset["Rating"] = dataset["Rating"].fillna('0')

In [31]:
dataset.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,art and design,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,art and design,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",art and design,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,art and design,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,art and design,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design Creativity,"June 20, 2018",1.1,4.4 and up

In [33]:
from re import L
def clean_label(label):
label = label.lower()
label = label.replace(' ','_')
label = label.replace('current_ver','current_version')
label = label.replace('android_ver','android_version')
return label

IndentationError: expected an indented block after function definition on line 2 (ipython-input-33-4255275581.py, line 3)

In [ ]:
dataset['rating'] = pd.to_numeric(dataset['rating'], errors='coerce').fillna(0)

In [42]:
from re import L
def clean_label(label):
    label = label.lower()
    label = label.replace(' ','_')
    label = label.replace('current_version','current_version')
    label = label.replace('android_version','android_version')
    return label

In [43]:
dataset.columns = pd.Series(dataset.columns).apply(clean_label)

In [44]:
dataset.head(3)

,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_versionsion,android_versionsion
0,Photo Editor & Candy Camera & Grid & ScrapBook,art and design,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,art and design,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",art and design,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up

In [45]:
dataset['current_versionsion'] = dataset['current_versionsion'].fillna('Unknown')

In [47]:
dataset['current_versionion'] = dataset['current_versionsion'].str.replace('Varies with device','Unknown')

In [48]:
dataset.head()

,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_versionsion,android_versionsion,current_versionion
0,Photo Editor & Candy Camera & Grid & ScrapBook,art and design,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,1.0.0
1,Coloring book moana,art and design,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2.0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",art and design,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,1.2.4
3,Sketch - Draw & Paint,art and design,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,Unknown
4,Pixel Draw - Number Art Coloring Book,art and design,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design Creativity,"June 20, 2018",1.1,4.4 and up,1.1

In [51]:
dataset['android_versionsion'] = dataset['android_versionsion'].fillna('Unknown')

In [52]:
dataset['type'] = dataset['type'].fillna('Unknown type')

In [53]:
dataset.head()

,app,category,rating,reviews,size,installs,type,price,content_rating,genres,last_updated,current_versionsion,android_versionsion,current_versionion
0,Photo Editor & Candy Camera & Grid & ScrapBook,art and design,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,1.0.0
1,Coloring book moana,art and design,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2.0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",art and design,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,1.2.4
3,Sketch - Draw & Paint,art and design,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,Unknown
4,Pixel Draw - Number Art Coloring Book,art and design,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design Creativity,"June 20, 2018",1.1,4.4 and up,1.1

In [54]:
dataset['category'] = dataset['category'].str.title()

In [56]:
dataset['category'] = dataset['category'].str.replace('And','&')

In [58]:
dataset['android_versionsion'] = dataset['android_versionsion'].str.replace('Varies with device','Unknow')
dataset['size'] = dataset['size'].str.replace('Varies with device','Unknown')
dataset['installs'] = dataset['installs'].str.replace('+','').str.replace(',','')
dataset['price'] = dataset['price'].str.replace('$','')
dataset['rating'] = dataset['rating'].astype(float)
dataset['price'] = dataset['price'].astype(float)
dataset.rename({'price':'price_usd'},axis=1, inplace = True)

In [59]:
dataset.head(6)

,app,category,rating,reviews,size,installs,type,price_usd,content_rating,genres,last_updated,current_versionsion,android_versionsion,current_versionion
0,Photo Editor & Candy Camera & Grid & ScrapBook,Art & Design,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,1.0.0
1,Coloring book moana,Art & Design,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2.0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",Art & Design,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,1.2.4
3,Sketch - Draw & Paint,Art & Design,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,Unknown
4,Pixel Draw - Number Art Coloring Book,Art & Design,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design Creativity,"June 20, 2018",1.1,4.4 and up,1.1
5,Paper flowers instructions,Art & Design,4.4,167,5.6M,50000,Free,0.0,Everyone,Art & Design,"March 26, 2017",1,2.3 and up,1

In [62]:
def category(element):
  if element > 100000:
    return 'Most high reviewed app'
  elif element < 100000 and element >= 20000:
    return 'High reviewed app'
  elif element < 20000 and element >= 5000:
    return 'Average reviewed app'
  else:
      return 'Low reviewed app'

In [63]:
dataset['reviews'].map(category).value_counts()

reviews
Low reviewed app          6047
Most high reviewed app    2169
High reviewed app         1539
Average reviewed app      1085
Name: count, dtype: int64

In [64]:
dataset['installs'] = dataset['installs'].astype(int)

In [65]:
def category(element):
  if element > 100000 :
    return 'Most downloaded app'
  elif element < 100000 and element >= 40000:
    return 'High downloaded app'
  elif element < 40000 and element >= 7000:
    return 'Average downloaded app'
  else:
     return 'Low downloaded app'

In [66]:
dataset['installs'].map(category).value_counts()

installs
Most downloaded app       4950
Low downloaded app        4357
Average downloaded app    1054
High downloaded app        479
Name: count, dtype: int64

In [67]:
free_apps = dataset[dataset['type'] == 'Free']

In [68]:
paid_apps = dataset[dataset['type'] == 'Paid']

In [69]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10840 entries, 0 to 10839
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   app                  10840 non-null  object
 1   category             10840 non-null  object
 2   rating               10840 non-null  float64
 3   reviews              10840 non-null  int64
 4   size                 10840 non-null  object
 5   installs             10840 non-null  int64
 6   type                 10840 non-null  object
 7   price_usd            10840 non-null  float64
 8   content_rating       10840 non-null  object
 9   genres               10840 non-null  object
 10  last_updated         10840 non-null  object
 11  current_versionsion  10840 non-null  object
 12  android_versionsion  10840 non-null  object
 13  current_versionion   10840 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 1.2+ MB

In [70]:
paid_apps

,app,category,rating,reviews,size,installs,type,price_usd,content_rating,genres,last_updated,current_versionsion,android_versionsion,current_versionion
234,TurboScan: scan documents and receipts in PDF,Business,4.7,11442,6.8M,100000,Paid,4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up,1.5.2
235,Tiny Scanner Pro: PDF Doc Scan,Business,4.8,10295,39M,100000,Paid,4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up,3.4.6
290,TurboScan: scan documents and receipts in PDF,Business,4.7,11442,6.8M,100000,Paid,4.99,Everyone,Business,"March 25, 2018",1.5.2,4.0 and up,1.5.2
291,Tiny Scanner Pro: PDF Doc Scan,Business,4.8,10295,39M,100000,Paid,4.99,Everyone,Business,"April 11, 2017",3.4.6,3.0 and up,3.4.6
427,Puffin Browser Pro,Communication,4.0,18247,Unknown,100000,Paid,3.99,Everyone,Communication,"July 5, 2018",7.5.3.20547,4.1 and up,7.5.3.20547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10734,FP VoiceBot,Family,0.0,17,157k,100,Paid,0.99,Mature 17+,Entertainment,"November 25, 2015",1.2,2.1 and up,1.2
10759,Fast Tract Diet,Health & Fitness,4.4,35,2.4M,1000,Paid,7.99,Everyone,Health & Fitness,"August 8, 2018",1.9.3,4.2 and up,1.9.3
10781,Trine 2: Complete Story,Game,3.8,252,11M,10000,Paid,16.99,Teen,Action,"February 27, 2015",2.22,5.0 and up,2.22
10784,"sugar, sugar",Family,4.2,1405,9.5M,10000,Paid,1.20,Everyone,Puzzle,"June 5, 2018",2.7,2.3 and up,2.7
10797,Word Search Tab 1 FR,Family,0.0,0,1020k,50,Paid,1.04,Everyone,Puzzle,"February 6, 2012",1.1,3.0 and up,1.1

In [72]:
free_apps

,app,category,rating,reviews,size,installs,type,price_usd,content_rating,genres,last_updated,current_versionsion,android_versionsion,current_versionion
0,Photo Editor & Candy Camera & Grid & ScrapBook,Art & Design,4.1,159,19M,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,1.0.0
1,Coloring book moana,Art & Design,3.9,967,14M,500000,Free,0.0,Everyone,Art & Design Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,2.0.0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",Art & Design,4.7,87510,8.7M,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,1.2.4
3,Sketch - Draw & Paint,Art & Design,4.5,215644,25M,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,Unknown
4,Pixel Draw - Number Art Coloring Book,Art & Design,4.3,967,2.8M,100000,Free,0.0,Everyone,Art & Design Creativity,"June 20, 2018",1.1,4.4 and up,1.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10835,Sya9a Maroc - FR,Family,4.5,38,53M,5000,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,1.48
10836,Fr. Mike Schmitz Audio Teachings,Family,5.0,4,3.6M,100,Free,0.0,Everyone,Education,"July 6, 2018",1,4.1 and up,1
10837,Parkinson Exercices FR,Medical,0.0,3,9.5M,1000,Free,0.0,Everyone,Medical,"January 20, 2017",1,2.2 and up,1
10838,The SCP Foundation DB fr nn5n,Books & Reference,4.5,114,Unknown,1000,Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Unknow,Unknown
10839,iHoroscope - 2018 Daily Horoscope & Astrology,Lifestyle,4.5,398307,19M,10000000,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Unknow,Unknown

In [73]:
paid_apps.groupby('category')['rating'].mean().sort_values(ascending = False)

category
News & Magazines     4.800000
Education            4.750000
Art & Design         4.733333
Entertainment        4.600000
Shopping             4.500000
Food & Drink         4.350000
Video Players        4.100000
Game                 4.056627
Lifestyle            4.026316
Sports               3.900000
Maps & Navigation    3.860000
Weather              3.825000
Family               3.642932
Personalization      3.585542
Medical              3.438532
Tools                3.367949
Parenting            3.350000
Communication        3.311111
Photography          3.309091
Business             3.300000
Health & Fitness     3.293750
Finance              2.929412
Travel & Local       2.733333
Productivity         2.703571
Social               2.466667
Dating               2.071429
Auto & Vehicles      1.533333
Books & Reference    1.221429
Events               0.000000
Libraries & Demo     0.000000
Name: rating, dtype: float64

In [74]:
dataset.to_csv('cleanedgoogleplaystoredata.csv', index = False)